matrix:
  include:
  - language=node_js
  node_js:
  - '10'
  dist: trusty
  addons:
    sonarcloud:
      organization: "sharkmir1"
  before_install:
  - cd frontend
  install:
  - yarn install
  script:
  - "./node_modules/.bin/eslint src"
  - yarn test --coverage --watchAll=false
  - sonar-scanner
env:
  global:
    secure: "Vt6J7m7bCKWrk+uC1aRQcYxBchZJ5THr9ZV2Djv/no9UDxO4wWbJPia6UeUcbXM5FHr9hGnGDTIkUooGgFxpAZY47igvIRfO/pz7IwrgQoUn1xH3hCtmOKJTsy3IT7DvwbpLOZGvLdO4uc2/EpkZLeUgyzdumIB0OG3vIeHCG5jBtoppRESNi07qeVbpWreOL9LIsm/5ypuB0JvHRXfIo2Fs4jcrXnJ898tEKisnfT4bcGiKlr/3mhu5dZ2b8q28xHXw0zi+bM2OisFviPrT1xGtVTRwovE5+aUpc01YkBCu4hpNUOvFVcUtmXazwO+xCV1AFYQeKVhQU5Oxj1kZYLLHq8GudYVBaRMxO/l/GZsTU6S6RTKndl5cNMMdIdY4ZxwWxTRLjaP1Z+mDwy0jqqgGYfXCzccCVOOXP8Gzmqnwyk2pq+fnzWHgenOX7mdnHXj1Uh0jLO1eF5zACWiviuAPfVEf1lT2rWgqDt0uI6jP3hZuIwi1siFZRI1DaUqlp1kmaOXx/LChGCxr7LwsO0G/7qqFpDFmZJgXOBUuZbfaRscGIIMnvObZ3hl3qd6/455g4EkMXJRZt5JaIO/KwFKseQZA4HWl/F6lpz8Eb+iNM9HC8kjndYeQ45h1qsF5zKksHaTHXs7Bg4pqd8MLndwpbD/fga0TFJd4DjOwpP8="
